### ISSUE TITLE
设置播放速率存在bug

### ISSUE THREAD

**Issue by purple-T** [QuintGao/GKWYMusic#2]
设置播放速率1.12和1.13有很大区别。 设置音乐1.12不起作用。

**Comment by QuintGao** [comment]
这应该是播放器的问题，我这里没有用到这个。

**Comment by purple-T** [comment]
@QuintGao  我也不知道哪里的问题，setPlayerPlayRate这个方法设置1.12和1.13的时候确实有问题，我把测试代码发给你， 你能看一下吗？

**Comment by purple-T** [comment]
我刚才用的就是最新的demo测试的

**Comment by QuintGao** [comment]
我上午试过了，确实有问题，FreeStreamer内部的代码我没有研究过，也不知道问题出在哪里。

**Comment by purple-T** [comment]
恩恩，是FreeStreamer内部的问题
